#version 430

struct S {
  float a;
  float b;
  float c;
  float d;
};

layout (set = 0, binding = 0) buffer outDat {
  S data[];
} OBuf;

layout (set = 0, binding = 1) buffer inDat {
  // vec4 data[];
  S data[];
} IBuf;

void main() {
  uint x = gl_GlobalInvocationID.x;
  S inval = IBuf.data[x];
  S val;
  val.a = inval.d;
  val.b = inval.b;
  val.c = inval.c;
  val.d = inval.a;
  OBuf.data[x] = val;
}
